name: golangci-lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: Jerome1337/golint-action@v1.0.2
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.18.5'      
      - name: lint
        run: make lint  
      - name: fmt
        run: make fmt
      - name: vet 
        run: make vet    