name: Integration tests

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3.3.0
        with:
          submodules: "true"

      - name: Get dependencies
        run: |
          go mod download

      - name: add curl for qsfs test
        run: sudo apt-get install curl

      - name: Test
        env:
          MNEMONICS: ${{ secrets.MNEMONICS }}
          NETWORK: dev
        run: go test -v ./integration_tests -tags integration
