name: Testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Setup Yggdrasil
      run: sudo apt-get update
          sudo apt-get install yggdrasil
          cd /etc/
          sed -i '/^  Peers .*/a tcp://62.210.85.80:39565' /etc/yggdrasil.conf
          sed -i '/^  Peers .*/a tls://95.216.5.243:18836' /etc/yggdrasil.conf
          sed -i '/^  Peers .*/a tls://192.99.145.61:58226' /etc/yggdrasil.conf
          sudo systemctl enable yggdrasil
          sudo systemctl start yggdrasil
  
    - name: Test
      env: 
        MNEMONICS: ${{ secrets.mnemonics }}
        NETWORK: ${{ secrets.network }}
      run: go test -v ./...