name: Testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Setup Yggdrasil
      run: sudo apt-get install yggdrasil
      run: sudo systemctl enable yggdrasil
      run: sudo systemctl start yggdrasil
  
    - name: Test
      env: 
        MNEMONICS: ${{ secrets.mnemonics }}
        NETWORK: ${{ secrets.network }}
      run: go test -v ./...